# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
inhibit_all_warnings!

target 'TIMRefreshEffectDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TIMRefreshEffectDemo
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'Reveal-SDK', :configurations => ['Debug']
    pod 'ReactiveCocoa', '2.5'

end
